[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
log = "0.4"  
env_logger = "0.11.6"